micronaut:
  application:
    name: hello-world
eureka:
  client:
    registration:
      enabled: true
      fail-fast: false
      retry-count: 10
      retry-delay: 5s
    defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8302}"
